title: dharavi.org
default_lang: en
author:
  name: 'EfSI 2023'
  email: nasheed@nyu.edu
taxonomies:
  - category
  - tag
  - author
metadata:
  description: 'Hola is a modern and stylish vCard website template. Designed to be a resume, vCard, portfolio template, it’s the perfect template for creative designers, developers, freelancers, photographer or any creative profession.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
